### PR TITLE
Add more mips build deps

### PR DESCRIPTION
**Pull request by SuperQ**
* Add mipsel compiler.
* Add mips64 / mips64el cross headers.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
I did some more testing with this, turns out we needed some more/different things.

The builder still fails, but for other reasons.
```
/go/bin/promu build --prefix .build/linux-mips64
 >   node_exporter
# runtime/cgo
/usr/lib/gcc-cross/mips-linux-gnu/6/libgcc_s.so.1: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
!! command failed: build -o .build/linux-mips64/node_exporter -ldflags -X github.com/prometheus/node_exporter/vendor/github.com/prometheus/common/version.Version=0.16.0 -X github.com/prometheus/node_exporter/vendor/github.com/prometheus/common/version.Revision=0662673ad6a626e93eb79bc784776a95164024a3 -X github.com/prometheus/node_exporter/vendor/github.com/prometheus/common/version.Branch=superq/update-build -X github.com/prometheus/node_exporter/vendor/github.com/prometheus/common/version.BuildUser=root@7c9a62fc9d5f -X github.com/prometheus/node_exporter/vendor/github.com/prometheus/common/version.BuildDate=20180807-16:27:09  -extldflags '-static' -a -tags 'netgo static_build' github.com/prometheus/node_exporter: exit status 2
```

**Comment by sdurrheimer** [comment]
Do we need to [declare new platforms in promu](https://github.com/prometheus/promu/blob/master/cmd/crossbuild.go#L44-L46) ?

Do we need to update the [builder.sh script](https://github.com/prometheus/golang-builder/blob/master/1.10/mips/rootfs/builder.sh#L31-L38) ?

**Comment by SuperQ** [comment]
@sdurrheimer Good question, I can experiment with that a bit.

**Comment by SuperQ** [comment]
@sdurrheimer I added support for 32bit MIPS in the `builder.sh`. The 64bit build still seems to be broken, but I'm not sure why Golang is not passing the correct compiler flags to the mips cross compiler to get a 64bit binary.

When I run the compiler on my test machine, I get this:

```
$ mips-linux-gnu-gcc  -print-multi-lib
.;
n32;@mabi=n32
64;@mabi=64
```

So in theory, it should work with `-m64`, but I get this when I try and add it to the CC env.

```
>> building binaries
/go/bin/promu build --prefix .build/linux-mips64
 >   node_exporter
# runtime/cgo
mips-linux-gnu-gcc: error: unrecognized command line option '-m64'
```

**Comment by SuperQ** [comment]
Ding, I figured it out.

```
.build/linux-mips/node_exporter:     ELF 32-bit MSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=8ae5ae32c27c987ebcba46ca322bba6733ef43d8, with debug_info, not stripped
.build/linux-mips64/node_exporter:   ELF 64-bit MSB executable, MIPS, MIPS64 rel2 version 1 (SYSV), statically linked, BuildID[sha1]=4a3d37d6cb19d0ae9fa3effe6c57d565498592ae, for GNU/Linux 3.2.0, with debug_info, not stripped
.build/linux-mips64le/node_exporter: ELF 64-bit LSB executable, MIPS, MIPS64 rel2 version 1 (SYSV), statically linked, BuildID[sha1]=88d12ed773244448019982141353821a8fac541d, for GNU/Linux 3.2.0, with debug_info, not stripped
.build/linux-mipsle/node_exporter:   ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=1bb5f68d2c60117970481abb45095114b812637b, with debug_info, not stripped
```

**Pull request merged**
