### PR TITLE
Add Go 1.9

### PR DESCRIPTION
**Pull request by sdurrheimer**

### CODE REVIEW

**Comment by sdurrheimer** [comment]
Current status: I don't understand why the build is failing. I can build it fine locally.

**Comment by beorn7** [comment]
I restarted the build, with the same effect.

Unsigned repository... not sure what to do about it.

**Comment by sdurrheimer** [comment]
Looks like emdebian packages are not signed correctly anymore.
We can open a ticket, but if I remember correctly, there are not well maintained anymore.

One solution is to add `[trusted=yes]` to the deb declaration to bypass it.

**Comment by beorn7** [comment]
Which in turn means our binaries are effectively unsigned...

**Comment by sdurrheimer** [comment]
Yup, what should we do ?

**Comment by grobie** [comment]
Ugh, installing unsigned packages from a HTTP source in our build infrastructure, would be cool to avoid that. The emdebian project looks indeed a bit stale, any alternatives to that?

Or maybe @TheTincho has any suggestions?

**Comment by TheTincho** [comment]
Hey all, sorry for not replying before, did not get a notification.

So, a few things about this:

* The error means that the signing key is not trusted, not that the distro is not signed;
* The method for retrieving the key is using non-TLS http, so it is the same security as setting `[trusted=yes]`.
* I was trying to find out why the signature verification fails, and found that emdebian is actually discontinued and the key has been revoked: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796331
* As said there, the crossbuilding stacks are now properly supported in debian, and all the packages you were installing from emdebian are available since stretch:
```
crossbuild-essential-arm64 | 12.3            | stable     | all
crossbuild-essential-arm64 | 12.4            | unstable   | all
crossbuild-essential-armel | 12.3            | stable     | all
crossbuild-essential-armel | 12.4            | unstable   | all
crossbuild-essential-armhf | 12.3            | stable     | all
crossbuild-essential-armhf | 12.4            | unstable   | all
linux-libc-dev-arm64-cross | 4.9.25-1cross1  | stable     | all
linux-libc-dev-arm64-cross | 4.12.13-1cross1 | unstable   | all
linux-libc-dev-armel-cross | 4.9.25-1cross1  | stable     | all
linux-libc-dev-armel-cross | 4.12.13-1cross1 | unstable   | all
linux-libc-dev-armhf-cross | 4.9.25-1cross1  | stable     | all
linux-libc-dev-armhf-cross | 4.12.13-1cross1 | unstable   | all
```

So the solution is simple: just remove the emdebian bits. I will prepare a PR now.

**Comment by sdurrheimer** [comment]
@TheTincho Thank you ! Nice to see the crossbuild toolchain in stretch.

**Pull request merged**
