### PR TITLE
Add goreleaser to the base image

### PR DESCRIPTION
**Pull request by SuperQ**
Allow use of goreleaser to build packages.

Signed-off-by: SuperQ <superq@gmail.com>

### CODE REVIEW

**Comment by roidelapluie** [comment]
Can we download the artefact instead? The sh script could tamper the whole image if changed. Dowloading the artefacts limits this risk.

**Comment by SuperQ** [comment]
Sure, I can change it to download directly.

**Comment by mrueg** [comment]
Alternatively, it might be easier to use multi-stages to get the binary:
FROM goreleaser/goreleaser:v0.169.0 as goreleaser 
...
COPY --from=goreleaser ....

**Comment by roidelapluie** [comment]
It is trickier to check the sha256sum of a container.

**Comment by SuperQ** [comment]
@roidelapluie The Docker build process takes care of validating the checksums for us.

**Review by roidelapluie — APPROVED** [review]

**Pull request merged**
