### PR TITLE
Update to CircleCI 2.0

### PR DESCRIPTION
**Pull request by sdurrheimer**
Signed-off-by: Steve Durrheimer <s.durrheimer@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
Did you try `setup_remote_docker` in the steps?

**Comment by sdurrheimer** [comment]
@SuperQ What the advantage of `docker image + setup_remote_docker` vs. `machine` ?

**Comment by sdurrheimer** [comment]
@SuperQ I will try out, currently looking for a good docker image to use. I was thinking about `circleci/buildpack-deps:stable-scm-dind` but it doesn't have the `make` command.

**Comment by sdurrheimer** [comment]
CircleCI docker build is always crashing with the following error :
```bash
Unexpected error running build task: CircleCI was unable to run the job runner because we were unable to execute commands in build container.

This typically means that the build container entrypoint or command is terminating the container prematurely, or interferring with executed commands.  Consider clearing entrypoint/command values and try again.
Original error: Internal Error - runner failed with exit code: 126
```

**Comment by SuperQ** [comment]
Strange, let's just stick to machine build for now.

**Pull request merged**
