### PR TITLE
Bump Go version

### PR DESCRIPTION
**Pull request by prombot**

### CODE REVIEW

**Comment by simonpasquier** [comment]
LGTM

**Comment by SuperQ** [comment]
As someone pointed out, there's some weird bugs with 1.14 and Linux kernel version checking. We might want to hold off until https://github.com/golang/go/issues/37436 is resolved.

**Comment by simonpasquier** [comment]
Agreed.

**Comment by roidelapluie** [comment]
At this stage, I'd like to keep 1.13 for the new release. It is also not clear what the effects of ' A consequence of the implementation of preemption is that on Unix systems, including Linux and macOS systems, programs built with Go 1.14 will receive more signals than programs built with earlier releases. This means that programs that use packages like syscall or golang.org/x/sys/unix will see more slow system calls fail with EINTR errors. Those programs will have to handle those errors in some way, most likely looping to try the system call again. For more information about this see man 7 signal for Linux systems or similar documentation for other systems. " can be.

**Comment by simonpasquier** [comment]
Note that projects wouldn't automatically switch to 1.14 even if this PR is merged (see [prometheus/.promu.yml](https://github.com/prometheus/prometheus/blob/df14bca6436743a57c9bd50c4bc4d50b1c87f77f/.promu.yml#L1-L4) for instance).

**Comment by roidelapluie** [comment]
That is interesting. So does it make sense to block this PR?

**Comment by codesome** [comment]
From what I understood from https://github.com/golang/go/issues/37436, 1.14 just highlights the kernel bug instead of silently failing and does not necessarily introduce that bug. So I am not sure why we are blocked on this upgrade. https://github.com/golang/go/wiki/LinuxKernelSignalVectorBug

**Comment by simonpasquier** [comment]
We could merge the PR but IIUC it's probably better to wait for [Go 1.14.1](https://github.com/golang/go/issues/37436#issuecomment-597360484) before switching projects to Go 1.14 as it would be easier for users to understand what happens.

**Comment by roidelapluie** [comment]
My point was to merge without updating the projects; to get the build docker image.

**Comment by simonpasquier** [comment]
@roidelapluie no problem, it was my understanding too. Decision deferred to @SuperQ and @sdurrheimer :)

**Comment by roidelapluie** [comment]
1.14.1 is out

**Comment by SuperQ** [comment]
I bumped this to 1.14.1

**Comment by roidelapluie** [comment]
Thanks all!

**Pull request merged**
