### PR TITLE
Add support for go 1.11

### LINKED ISSUE #49: Add Go 1.11
To use the new user annotation API of the `runtime/trace` package (see https://github.com/prometheus/prometheus/pull/4568#issuecomment-419405220). And also to experiment with modules.

I'll send a PR soon.

### PR DESCRIPTION
**Pull request by simonpasquier**
Closes #49

### CODE REVIEW

**Comment by simonpasquier** [comment]
@sdurrheimer this isn't directly related to this PR but the CI failed because `OSXCROSS_SDK_URL` isn't set (https://circleci.com/gh/prometheus/golang-builder/165). This relates probably to the migration from Circle CI 1.0 to 2.0 and the fact that by default, builds from forked pull requests can't access secrets (see https://circleci.com/docs/2.0/oss/#pass-secrets-to-builds-from-forked-pull-requests). I've pushed my branch to the parent repository and it solves the issue for me but any external contributor will be impacted AFAICT.

**Comment by sdurrheimer** [comment]
LGTM but usually we only keep 2 golang versions. We should probably remove Go 1.9.

**Comment by simonpasquier** [comment]
I thought that `node_exporter` was still using 1.9 but it isn't the case anymore since a month ago. I'll amend the PR to keep only 1.10 and 1.11.

**Comment by SuperQ** [comment]
Yes, we think we may have gotten to the bottom of the 1.10.x CGO crashing. At worst, we've disabled the collector that appears to be the problem.

**Pull request merged**
