### PR TITLE
Bump Go version

### PR DESCRIPTION
**Pull request by prombot**

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
LGTM

**Comment by SuperQ** [comment]
@roidelapluie Yay, it works again.

**Comment by roidelapluie** [comment]
1.16.7 ???

**Comment by SuperQ** [comment]
Ahh, it looks like the README got messed up in the last major version upgrade, probably due to the bugs in the bump script.

**Comment by roidelapluie** [comment]
1.16.8 is actually fine

**Comment by roidelapluie** [comment]
oh I see the readme now

**Pull request merged**
